/* Rebuild index.json from whatever files are actually in the repository.

   The catalog is DERIVED, never hand-edited. Two reasons: submissions
   would otherwise all collide on the same file, and a hand-maintained
   index drifts out of step with the folders it describes.

   Also seeds stats.json entries for anything new, so a freshly merged
   pack has a score of zero rather than no score at all. Existing
   tallies are never touched here - the voting pipeline owns those.

   Usage: node .github/scripts/build-index.mjs [--check]
     --check  exit 1 if the files on disk are out of date, change nothing
*/

import fs from "node:fs";
import path from "node:path";
import { listContentFiles, countsOf, checkShape } from "./lib.mjs";

const root = process.cwd();
const check = process.argv.includes("--check");

const entries = [];
const problems = [];

for (const f of listContentFiles(root)) {
  let data;
  try {
    data = JSON.parse(fs.readFileSync(path.join(root, f.rel), "utf8"));
  } catch (err) {
    problems.push(`${f.rel}: not valid JSON (${err.message})`);
    continue;
  }

  const shape = checkShape(f.type, data);
  if (!shape.ok) {
    problems.push(`${f.rel}: ${shape.error}`);
    continue;
  }

  const meta = (data.meta && typeof data.meta === "object") ? data.meta : {};
  const id = String(meta.id || f.name.replace(/\.json$/, ""));

  entries.push({
    id,
    type: f.type,
    title: String(meta.title || id),
    description: String(meta.description || ""),
    author: String(meta.author || "Anonymous"),
    contributedAt: String(meta.contributedAt || data.exportedAt || ""),
    updatedAt: String(data.exportedAt || meta.contributedAt || ""),
    schema: Number(data.schema) || null,
    counts: countsOf(f.type, data),
    path: f.rel,
  });
}

if (problems.length) {
  console.error("Refusing to build an index over broken files:");
  for (const p of problems) console.error("  " + p);
  process.exit(1);
}

/* Stable order so the file does not churn between runs for no reason. */
entries.sort((a, b) => a.type.localeCompare(b.type) || a.id.localeCompare(b.id));

const indexPath = path.join(root, "index.json");
const prev = fs.existsSync(indexPath) ? JSON.parse(fs.readFileSync(indexPath, "utf8")) : {};

const index = {
  schema: 1,
  generatedAt: new Date().toISOString(),
  note: "Derived file, regenerated by .github/workflows/build-index.yml on every push to main. Do not hand-edit.",
  entries,
};

/* Compare ignoring generatedAt, otherwise every run looks like a change
   and the repository fills with empty commits. */
const same = (a, b) =>
  JSON.stringify({ ...a, generatedAt: null }) === JSON.stringify({ ...b, generatedAt: null });

const indexChanged = !same(prev, index);

/* stats.json: add a zero row for anything new, leave real tallies alone. */
const statsPath = path.join(root, "stats.json");
const stats = fs.existsSync(statsPath)
  ? JSON.parse(fs.readFileSync(statsPath, "utf8"))
  : { schema: 1, generatedAt: new Date().toISOString(), scores: {} };
if (!stats.scores || typeof stats.scores !== "object") stats.scores = {};

let statsChanged = false;
for (const e of entries) {
  if (!stats.scores[e.id]) {
    stats.scores[e.id] = { up: 0, down: 0, score: 0 };
    statsChanged = true;
  }
}
for (const id of Object.keys(stats.scores)) {
  if (!entries.some((e) => e.id === id)) {
    delete stats.scores[id];
    statsChanged = true;
  }
}

if (check) {
  if (indexChanged || statsChanged) {
    console.error("index.json or stats.json is out of date. Run:");
    console.error("  node .github/scripts/build-index.mjs");
    process.exit(1);
  }
  console.log(`Up to date. ${entries.length} entries.`);
  process.exit(0);
}

if (indexChanged) {
  fs.writeFileSync(indexPath, JSON.stringify(index, null, 2) + "\n");
  console.log(`index.json rebuilt: ${entries.length} entries.`);
} else {
  console.log("index.json already up to date.");
}

if (statsChanged) {
  fs.writeFileSync(statsPath, JSON.stringify(stats, null, 2) + "\n");
  console.log("stats.json seeded for new entries.");
} else {
  console.log("stats.json already up to date.");
}

console.log(`CHANGED=${indexChanged || statsChanged ? "yes" : "no"}`);
